const DataByItem = [
  {
    id: 1,
    name: 'CAB-O-SIL',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 2,
    name: 'CELVOLIT 1602',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 3,
    name: 'CRAYVALLAC SF',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 4,
    name: 'SYNOLAC T62',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 5,
    name: 'TEGO FOAMEX 825',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 6,
    name: 'TEGO TWIN 4100',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 7,
    name: 'CAB-O-SIL',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 8,
    name: 'CELVOLIT 1602',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 9,
    name: 'CRAYVALLAC SF',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 10,
    name: 'SYNOLAC T62',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 11,
    name: 'TEGO FOAMEX 825',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 12,
    name: 'TEGO TWIN 4100',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 13,
    name: 'CAB-O-SIL',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 14,
    name: 'CELVOLIT 1602',
    status: ['Open PO', 'Scheduled'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 15,
    name: 'CRAYVALLAC SF',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 16,
    name: 'SYNOLAC T62',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 17,
    name: 'TEGO FOAMEX 825',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
  {
    id: 18,
    name: 'TEGO TWIN 4100',
    status: ['Open PO'],
    TDSlink: 'http://tdslink.com',
    SDSlink: 'http://sdslink.com',
  },
];

export default DataByItem;
